spring.application.name=TP1-PB_monolito

# H2 - Banco de dados em memória
spring.datasource.url=${DB_URL:jdbc:h2:mem:infnethubdb}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:}
# Console H2 - acessar em: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o DataLoader rode após o Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true
